version: '3.8'

services:
    db:
        container_name: postgres_fin_manager
        image: postgres:14.0-alpine
        restart: always
        environment:
            - POSTGRES_USER=${TYPEORM_USERNAME}
            - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
            - POSTGRES_DB=${TYPEORM_DATABASE}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - ${TYPEORM_PORT}:${TYPEORM_PORT}
    backend:
        container_name: backend_fin_manager
        image: nestjs-api-dev:1.0.0
        build: 
            context: ./
        depends_on:
            - db
        restart: unless-stopped
        ports:
            - ${API_PORT}:3000
        environment:
            - API_PORT=${API_PORT}
            - API_HOST=${API_HOST}
            - TYPEORM_HOST=db
            - TYPEORM_DB_TYPE=${TYPEORM_DB_TYPE}
            - TYPEORM_USERNAME=${TYPEORM_USERNAME}
            - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
            - TYPEORM_DATABASE=${TYPEORM_DATABASE}
            - TYPEORM_PORT=${TYPEORM_PORT}
